title: TEE-assisted Confidential Smart Contracts
description: This page lists blockchain projects that use the trusted execution environment (TEE) to achieve confidential smart contracts.

domain: "tcsc.github.io"
baseurl: "/tcsc"

github_username: rjgeek
github_repo: tcsc

markdown: kramdown

